### ISSUE TITLE
Adding Baud Rate Adaptive Function

### ISSUE THREAD

**Issue by wangshujun-tj** [bluerobotics/ping-firmware#14]
It is known that the recently launched STM32 has supported the baud rate self-control capability, considering adding corresponding items in the protocol.

You can wait for a specific frame after opening.

The function is restarted after successive frame errors.

According to the requirement of the first data enabled by stm32, we can consider adding a specific character header, which will be automatically ignored in the original protocol.

**Comment by patrickelectric** [comment]
Hi @wangshujun-tj and thank you for your input.
Indeed this is in our plans, we are certainly going to do a release with this feature.

**Comment by patrickelectric** [comment]
Done in 3.28
